"use strict";
const $=id=>document.getElementById(id), canvas=$("deviceCanvas"),ctx=canvas.getContext("2d");
const inputIds=["experimentPreset","projectName","widthNm","heightNm","thicknessNm","nx","ny","material","temperatureK","currentNa","fieldT","laserPowerNw","laserSigmaNm","dtFs","steps","sampleEvery","selfField","scalarPotential","normalContacts","junctionCenterNm","junctionWidthNm","junctionSuppression","targetXNm","targetYNm","followXNm","followYNm","beamSpeed","targetToleranceNm","microwaveEnabled","driveDcNa","driveAcNa","driveFrequencyGhz","drivePhase"];
const PRESETS={
  basic_film:{title:"Basic film",description:"A clean rectangular TDGL film for field, current, vortex, hole, and relaxation studies.",runner:"diagnostics",junction:false,feedback:false,values:{projectName:"basic_film",widthNm:100,heightNm:70,nx:161,ny:113,temperatureK:14,currentNa:0,fieldT:0,laserPowerNw:0,laserSigmaNm:8,dtFs:10,steps:500,sampleEvery:5,selfField:false,normalContacts:false},vortices:[],laser:[],holes:[]},
  current_vortex:{title:"Current-driven vortex",description:"One vortex in a transport film with adjustable terminal current and magnetic field.",runner:"diagnostics",junction:false,feedback:false,values:{projectName:"current_driven_vortex",widthNm:120,heightNm:80,nx:121,ny:81,temperatureK:14,currentNa:10,fieldT:.2,laserPowerNw:0,dtFs:10,steps:1000,sampleEvery:5,normalContacts:true},vortices:[{x:60,y:40,charge:1,core:2}],laser:[],holes:[]},
  optical_tweezer:{title:"Optical tweezer",description:"Feedback-guided two-temperature laser transport of a selected vortex; add other vortices to study collective motion.",runner:"feedback",junction:false,feedback:true,values:{projectName:"optical_tweezer",widthNm:150,heightNm:150,nx:151,ny:151,temperatureK:13,currentNa:0,fieldT:.2,laserPowerNw:500,laserSigmaNm:10,dtFs:10,steps:10000,sampleEvery:10,targetXNm:0,targetYNm:10,followXNm:0,followYNm:17.5,beamSpeed:2000,targetToleranceNm:.25,normalContacts:true},vortices:[{x:75,y:75,charge:1,core:2}],laser:[],holes:[]},
  optical_junction:{title:"Optical junction transport",description:"Pull a left-bank vortex toward a central weak link while vortices on the other bank evolve freely.",runner:"feedback",junction:true,feedback:true,values:{projectName:"optical_junction_vortex",widthNm:150,heightNm:100,nx:151,ny:101,temperatureK:13,currentNa:0,fieldT:.5,laserPowerNw:500,laserSigmaNm:10,dtFs:10,steps:20000,sampleEvery:10,junctionCenterNm:75,junctionWidthNm:2,junctionSuppression:.7,targetXNm:30,targetYNm:0,followXNm:17.5,followYNm:0,beamSpeed:2000,targetToleranceNm:.5,normalContacts:true},vortices:[{x:37.5,y:50,charge:1,core:2},{x:112.5,y:50,charge:1,core:2}],laser:[],holes:[]},
  sns_junction:{title:"SNS / weak-link junction",description:"A resolved central weak link for phase, current-voltage, vortex, and optional microwave studies.",runner:"diagnostics",junction:true,feedback:false,values:{projectName:"sns_weak_link",widthNm:100,heightNm:50,nx:201,ny:101,temperatureK:14,currentNa:10,fieldT:0,junctionCenterNm:50,junctionWidthNm:2.5,junctionSuppression:.7,dtFs:10,steps:2000,sampleEvery:2,normalContacts:true},vortices:[],laser:[],holes:[]},
  squid_ring:{title:"Perforated ring / SQUID",description:"A film with a central aperture for fluxoid, circulating-current, and interference experiments.",runner:"diagnostics",junction:false,feedback:false,values:{projectName:"squid_ring",widthNm:120,heightNm:120,nx:121,ny:121,temperatureK:14,currentNa:0,fieldT:.1,dtFs:10,steps:1500,sampleEvery:5,selfField:true,normalContacts:false},vortices:[],laser:[],holes:[{shape:"circle",name:"central_hole",x:60,y:60,radius:18}]},
  hotspot:{title:"Two-temperature hotspot",description:"A stationary optical pulse for electron-phonon heating, recovery, and superconducting suppression.",runner:"diagnostics",junction:false,feedback:false,values:{projectName:"two_temperature_hotspot",widthNm:100,heightNm:100,nx:101,ny:101,temperatureK:13,currentNa:0,fieldT:0,laserPowerNw:500,laserSigmaNm:10,dtFs:10,steps:2000,sampleEvery:5,normalContacts:false},vortices:[],laser:[{x:50,y:50,time:0,power:1},{x:50,y:50,time:20000,power:1}],holes:[]}
};
let state={tool:"select",preset:"basic_film",holes:[],vortices:[],laser:[],selected:null,dragging:false};
const n=id=>Number($(id).value), cleanName=()=>($("projectName").value.trim().replace(/[^a-zA-Z0-9_-]+/g,"_")||"drawn_experiment");
const meters=nm=>nm*1e-9, femto=fs=>fs*1e-15;
function viewport(){const w=canvas.clientWidth,h=canvas.clientHeight,p=46,W=n("widthNm"),H=n("heightNm"),s=Math.min((w-2*p)/W,(h-2*p)/H);return {p,s,ox:(w-W*s)/2,oy:(h-H*s)/2,W,H};}
function toCanvas(x,y){const v=viewport();return [v.ox+x*v.s,v.oy+(v.H-y)*v.s]}
function toDevice(x,y){const v=viewport(),r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(v.W,(x-r.left-v.ox)/v.s)),y:Math.max(0,Math.min(v.H,v.H-(y-r.top-v.oy)/v.s))}}
function resize(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function draw(){const v=viewport();ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);const [x0,y0]=toCanvas(0,v.H);ctx.fillStyle="#152431";ctx.strokeStyle="#6f879b";ctx.lineWidth=1;ctx.fillRect(x0,y0,v.W*v.s,v.H*v.s);ctx.strokeRect(x0,y0,v.W*v.s,v.H*v.s);const preset=PRESETS[state.preset];if(preset&&preset.junction){const [jx]=toCanvas(n("junctionCenterNm"),0);ctx.fillStyle="#45d2d033";ctx.fillRect(jx-n("junctionWidthNm")*v.s/2,y0,n("junctionWidthNm")*v.s,v.H*v.s);ctx.strokeStyle="#54d6d0";ctx.setLineDash([5,4]);ctx.strokeRect(jx-n("junctionWidthNm")*v.s/2,y0,n("junctionWidthNm")*v.s,v.H*v.s);ctx.setLineDash([])}
  ctx.strokeStyle="#22394a";ctx.lineWidth=.6;for(let i=1;i<10;i++){let x=x0+i*v.W*v.s/10,y=y0+i*v.H*v.s/10;ctx.beginPath();ctx.moveTo(x,y0);ctx.lineTo(x,y0+v.H*v.s);ctx.stroke();ctx.beginPath();ctx.moveTo(x0,y);ctx.lineTo(x0+v.W*v.s,y);ctx.stroke()}
  state.holes.forEach((o,i)=>{const [x,y]=toCanvas(o.x,o.y);ctx.fillStyle="#070b0f";ctx.strokeStyle=selected("hole",i)?"#54d6d0":"#71889b";ctx.lineWidth=selected("hole",i)?3:1.3;ctx.beginPath();if(o.shape==="circle")ctx.arc(x,y,o.radius*v.s,0,Math.PI*2);else ctx.rect(x-o.width*v.s/2,y-o.height*v.s/2,o.width*v.s,o.height*v.s);ctx.fill();ctx.stroke()});
  if(state.laser.length>1){ctx.strokeStyle="#ffd166";ctx.lineWidth=2.5;ctx.setLineDash([8,5]);ctx.beginPath();state.laser.forEach((o,i)=>{const [x,y]=toCanvas(o.x,o.y);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.setLineDash([])}
  state.laser.forEach((o,i)=>{const [x,y]=toCanvas(o.x,o.y);ctx.fillStyle="#ffd166";ctx.strokeStyle=selected("laser",i)?"#fff":"#9d7920";ctx.lineWidth=selected("laser",i)?3:1;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#0b1016";ctx.font="10px sans-serif";ctx.textAlign="center";ctx.fillText(i+1,x,y+3)});
  state.vortices.forEach((o,i)=>{const [x,y]=toCanvas(o.x,o.y),c=o.charge>0?"#ff646e":"#57a8ff";ctx.strokeStyle=c;ctx.lineWidth=selected("vortex",i)?4:2.5;ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.stroke();ctx.fillStyle=c;ctx.font="bold 13px sans-serif";ctx.textAlign="center";ctx.fillText(o.charge>0?"+":"−",x,y+4)});
  ctx.fillStyle="#91a6b9";ctx.font="12px sans-serif";ctx.textAlign="center";ctx.fillText(`${v.W} nm`,x0+v.W*v.s/2,y0+v.H*v.s+26);ctx.save();ctx.translate(x0-28,y0+v.H*v.s/2);ctx.rotate(-Math.PI/2);ctx.fillText(`${v.H} nm`,0,0);ctx.restore();validate();renderList()}
function selected(type,index){return state.selected&&state.selected.type===type&&state.selected.index===index}
function hit(p){let best=null,dist=Infinity;state.vortices.forEach((o,i)=>consider("vortex",i,Math.hypot(p.x-o.x,p.y-o.y),4));state.laser.forEach((o,i)=>consider("laser",i,Math.hypot(p.x-o.x,p.y-o.y),4));state.holes.forEach((o,i)=>{let d=o.shape==="circle"?Math.hypot(p.x-o.x,p.y-o.y):Math.max(Math.abs(p.x-o.x)-o.width/2,Math.abs(p.y-o.y)-o.height/2);consider("hole",i,Math.max(0,d),5)});return best;function consider(type,index,d,limit){if(d<limit&&d<dist){dist=d;best={type,index}}}}
function object(sel=state.selected){if(!sel)return null;return sel.type==="hole"?state.holes[sel.index]:sel.type==="vortex"?state.vortices[sel.index]:state.laser[sel.index]}
canvas.addEventListener("pointerdown",e=>{const p=toDevice(e.clientX,e.clientY);if(state.tool==="select"){state.selected=hit(p);state.dragging=!!state.selected;renderEditor();draw();return}if(state.tool==="circle")state.holes.push({shape:"circle",name:`hole_${state.holes.length+1}`,x:p.x,y:p.y,radius:n("holeRadiusNm")});if(state.tool==="rectangle")state.holes.push({shape:"rectangle",name:`hole_${state.holes.length+1}`,x:p.x,y:p.y,width:n("holeWidthNm"),height:n("holeHeightNm")});if(state.tool.startsWith("vortex"))state.vortices.push({x:p.x,y:p.y,charge:state.tool.endsWith("+")?1:-1,core:n("coreCells")});if(state.tool==="laser")state.laser.push({x:p.x,y:p.y,time:state.laser.length*n("pathIntervalFs"),power:n("pointPower")});state.selected={type:state.tool.startsWith("vortex")?"vortex":state.tool==="laser"?"laser":"hole",index:(state.tool.startsWith("vortex")?state.vortices:state.tool==="laser"?state.laser:state.holes).length-1};renderEditor();draw()});
canvas.addEventListener("pointermove",e=>{if(!state.dragging||!state.selected)return;const p=toDevice(e.clientX,e.clientY),o=object();o.x=p.x;o.y=p.y;renderEditor();draw()});window.addEventListener("pointerup",()=>state.dragging=false);
function setTool(tool){state.tool=tool;document.querySelectorAll("[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===tool));$("modeLabel").textContent="Mode: "+document.querySelector(`[data-tool='${tool}']`).textContent;}
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function renderEditor(){const box=$("selectionEditor"),o=object();if(!o){box.className="empty";box.textContent="Nothing selected.";return}box.className="";let fields=`<div class="grid2"><label>X (nm)<input data-prop="x" type="number" step="0.1" value="${o.x}"></label><label>Y (nm)<input data-prop="y" type="number" step="0.1" value="${o.y}"></label>`;if(state.selected.type==="hole"){fields+=`<label>Name<input data-prop="name" value="${o.name}"></label>`+(o.shape==="circle"?`<label>Radius (nm)<input data-prop="radius" type="number" value="${o.radius}"></label>`:`<label>Width (nm)<input data-prop="width" type="number" value="${o.width}"></label><label>Height (nm)<input data-prop="height" type="number" value="${o.height}"></label>`)}if(state.selected.type==="vortex")fields+=`<label>Charge<select data-prop="charge"><option value="1" ${o.charge>0?"selected":""}>+1</option><option value="-1" ${o.charge<0?"selected":""}>−1</option></select></label><label>Core (cells)<input data-prop="core" type="number" value="${o.core}"></label>`;if(state.selected.type==="laser")fields+=`<label>Time (fs)<input data-prop="time" type="number" value="${o.time}"></label><label>Power fraction<input data-prop="power" type="number" min="0" max="1" step="0.05" value="${o.power}"></label>`;box.innerHTML=fields+`</div><button id="deleteSelected" class="delete">Delete selected</button>`;box.querySelectorAll("[data-prop]").forEach(el=>el.oninput=()=>{o[el.dataset.prop]=el.dataset.prop==="name"?el.value:Number(el.value);draw()});$("deleteSelected").onclick=removeSelected}
function removeSelected(){if(!state.selected)return;const a=state.selected.type==="hole"?state.holes:state.selected.type==="vortex"?state.vortices:state.laser;a.splice(state.selected.index,1);state.selected=null;renderEditor();draw()}
const BASE_VALUES={widthNm:100,heightNm:70,thicknessNm:2,nx:101,ny:71,material:"NbN_tdgl_reference",temperatureK:14,currentNa:0,fieldT:0,laserPowerNw:0,laserSigmaNm:8,dtFs:10,steps:500,sampleEvery:5,selfField:false,scalarPotential:true,normalContacts:false,junctionCenterNm:50,junctionWidthNm:2,junctionSuppression:.7,targetXNm:10,targetYNm:0,followXNm:15,followYNm:0,beamSpeed:2000,targetToleranceNm:.5,microwaveEnabled:false,driveDcNa:0,driveAcNa:100,driveFrequencyGhz:50,drivePhase:0};
function clone(value){return JSON.parse(JSON.stringify(value))}
function updateContext(){state.preset=$("experimentPreset").value;const p=PRESETS[state.preset];$("presetDescription").textContent=p.description;$("junctionControls").classList.toggle("hidden",!p.junction);$("feedbackControls").classList.toggle("hidden",!p.feedback);$("microwaveControls").classList.toggle("hidden",!p.junction);$("downloadDiagnostics").textContent=p.runner==="feedback"?"Feedback experiment JSON":"Diagnostics JSON";draw()}
function applyPreset(){const key=$("experimentPreset").value,p=PRESETS[key];Object.entries({...BASE_VALUES,...p.values}).forEach(([id,value])=>{const el=$(id);if(el)el.type==="checkbox"?el.checked=!!value:el.value=value});state.preset=key;state.holes=clone(p.holes);state.vortices=clone(p.vortices);state.laser=clone(p.laser);state.selected=null;renderEditor();updateContext();resize();$("status").textContent=`Loaded ${p.title}. Adjust any highlighted controls or draw additional objects.`}
function renderList(){const rows=[];state.holes.forEach((o,i)=>rows.push(row("hole",i,`${o.shape} ${o.name}`)));state.vortices.forEach((o,i)=>rows.push(row("vortex",i,`${o.charge>0?"+":"−"} vortex`)));state.laser.forEach((o,i)=>rows.push(row("laser",i,`laser ${i+1} · ${o.time} fs`)));$("objectList").innerHTML=rows.join("")||'<div class="empty">No objects yet.</div>';document.querySelectorAll(".object-row").forEach(el=>el.onclick=()=>{state.selected={type:el.dataset.type,index:Number(el.dataset.index)};setTool("select");renderEditor();draw()});function row(t,i,label){return `<div class="object-row ${selected(t,i)?"selected":""}" data-type="${t}" data-index="${i}"><span>${label}</span><small>${object({type:t,index:i}).x.toFixed(1)}, ${object({type:t,index:i}).y.toFixed(1)} nm</small></div>`}}
function validate(){const issues=[],W=n("widthNm"),H=n("heightNm"),dx=W/(n("nx")-1),dy=H/(n("ny")-1),preset=PRESETS[state.preset];state.holes.forEach((o,i)=>{const hw=o.shape==="circle"?o.radius:o.width/2,hh=o.shape==="circle"?o.radius:o.height/2;if(o.x-hw<=0||o.x+hw>=W||o.y-hh<=0||o.y+hh>=H)issues.push(`Hole ${i+1} must lie strictly inside the film.`);if(Math.min(hw,hh)<2*Math.max(dx,dy))issues.push(`Hole ${i+1} is resolved by fewer than about four cells.`)});for(let i=1;i<state.laser.length;i++)if(state.laser[i].time<=state.laser[i-1].time)issues.push("Laser waypoint times must strictly increase.");state.laser.forEach((p,i)=>{if(p.power<0||p.power>1)issues.push(`Laser point ${i+1} power must be between 0 and 1.`)});if(n("laserPowerNw")>0&&n("laserSigmaNm")<2*Math.max(dx,dy))issues.push("Laser sigma is resolved by fewer than two cells.");if(preset.feedback&&!state.vortices.length)issues.push("Feedback experiments need at least one vortex; the first vortex is tracked.");if(state.preset==="hotspot"&&!state.laser.length)issues.push("The hotspot default needs at least one laser waypoint.");if(preset.junction&&(n("junctionCenterNm")-n("junctionWidthNm")/2<=0||n("junctionCenterNm")+n("junctionWidthNm")/2>=W))issues.push("The junction must lie strictly inside the film.");if(preset.junction&&n("junctionWidthNm")<Math.max(dx,dy))issues.push("The junction is narrower than one mesh interval.");if(preset.feedback&&Math.hypot(n("targetXNm"),n("targetYNm"))===0)issues.push("Feedback target displacement must be nonzero.");if(preset.feedback&&Math.hypot(n("followXNm"),n("followYNm"))===0)issues.push("Laser follow offset must be nonzero.");if($("microwaveEnabled").checked&&n("driveFrequencyGhz")*1e9*femto(n("dtFs"))>.02)issues.push("Microwave drive has fewer than 50 integration steps per cycle.");$("validation").innerHTML=issues.length?issues.map(x=>`<li>${x}</li>`).join(""):'<li class="ok">Configuration is structurally ready to export.</li>';return issues}
function geometry(){const name=cleanName();return {type:"rectangle",name,width:meters(n("widthNm")),height:meters(n("heightNm")),thickness:meters(n("thicknessNm")),nx:Math.round(n("nx")),ny:Math.round(n("ny")),regions:[{name:`${name} film`,region_type:"superconductor",material:$("material").value}],holes:state.holes.map(o=>o.shape==="circle"?{name:o.name,shape:o.shape,x:meters(o.x),y:meters(o.y),radius:meters(o.radius)}:{name:o.name,shape:o.shape,x:meters(o.x),y:meters(o.y),width:meters(o.width),height:meters(o.height)}),contacts:[{name:"left_current",contact_type:"current",x:0,y:0,x_size:0,y_size:meters(n("heightNm"))},{name:"right_current",contact_type:"current",x:meters(n("widthNm")),y:0,x_size:0,y_size:meters(n("heightNm"))}]}}
function simulation(){const name=cleanName(),normal=$("normalContacts").checked,boundary=normal?"normal_contact_mask":"insulating",duration=femto(n("dtFs")*n("steps")),preset=PRESETS[state.preset];const result={name,geometry:`${name}_geometry.json`,material:`${$("material").value}.json`,temperature:n("temperatureK"),current:{value:n("currentNa")*1e-9,units:"A"},time:{duration,dt:femto(n("dtFs"))},thermal:{bath_temperature:n("temperatureK"),model:"two_temperature",electron_heat_capacity_fraction:.5,electron_thermal_conductivity_fraction:.7,electron_phonon_coupling_W_m3_K:1e16,phonon_escape_rate_per_s:1e10,max_substep:1e-13,stability_safety_factor:.9},laser:{enabled:state.laser.length>0&&!preset.feedback,absorbed_power_W:n("laserPowerNw")*1e-9,sigma_m:meters(n("laserSigmaNm")),repeat_path:false,waypoints:state.laser.map(p=>({time_s:femto(p.time),x_m:meters(p.x),y_m:meters(p.y),power_fraction:p.power}))},pinning:{enabled:false,maximum_suppression:1,sites:[]},electrical:{drive_mode:"current",source_contact:"left_current",sink_contact:"right_current",reference_voltage:0,normal_conductivity_model:"condensate_depletion",solver:{backend:"sparse_direct",tolerance:1e-11,max_iterations:100000,omega:1.7,residual_check_interval:10}},electromagnetic:{include_self_field:$("selfField").checked,include_displacement_current:false,screening_tolerance:1e-4,screening_max_iterations:100,screening_step_size:.3,screening_source_stride:1},tdgl:{normalization:"pytdgl",temperature_model:"tc_over_t_minus_one",u:5.79,gamma:0,kappa:1,include_scalar_potential:$("scalarPotential").checked,max_normalized_timestep:.01,stability_safety_factor:.8,time_integrator:"heun"},boundaries:{left:{type:"fixed_temperature",temperature:n("temperatureK")},right:{type:"fixed_temperature",temperature:n("temperatureK")},top:{type:"insulating"},bottom:{type:"insulating"}},tdgl_boundaries:{left:{type:boundary},right:{type:boundary},top:{type:"insulating"},bottom:{type:"insulating"}}};if(preset.junction)result.josephson={enabled:true,center_x_m:meters(n("junctionCenterNm")),width_m:meters(n("junctionWidthNm")),coefficient_suppression:n("junctionSuppression")};return result}
function diagnostics(){const name=cleanName(),preset=PRESETS[state.preset],runner=preset.runner==="feedback"?"tools/optical_transport_overnight.py":"tools/tdgl_diagnostics.py",experimentPath=`tools/config/${name}_experiment.json`,vortices=state.vortices.map(v=>({x_fraction:v.x/n("widthNm"),y_fraction:v.y/n("heightNm"),charge:v.charge,core_radius_cells:v.core})),documentation={purpose:`Generated ${preset.title} experiment. Review physical scales and convergence before interpretation.`,preset:state.preset,runner,run_command:`python ${runner} --config ${experimentPath}`,coordinate_units:"Editor nanometres were converted to SI metres."};if(preset.runner==="feedback"){const tracked=state.vortices[0]||{x:n("widthNm")/2,y:n("heightNm")/2};return {_documentation:documentation,simulation_config:`configs/simulations/${name}_simulation.json`,applied_field_T:n("fieldT"),initial_vortices:vortices,seed_position_m:[meters(tracked.x),meters(tracked.y)],target:{displacement_m:[meters(n("targetXNm")),meters(n("targetYNm"))],tolerance_nm:n("targetToleranceNm")},laser:{absorbed_power_W:n("laserPowerNw")*1e-9,spot_sigma_m:meters(n("laserSigmaNm")),offset_m:[meters(n("followXNm")),meters(n("followYNm"))],max_speed_m_s:n("beamSpeed"),update_every_steps:1},electrical_drive:{enabled:$("microwaveEnabled").checked,dc_current_A:n("driveDcNa")*1e-9,ac_amplitude_A:n("driveAcNa")*1e-9,frequency_Hz:n("driveFrequencyGhz")*1e9,phase_rad:n("drivePhase")},pinning:{enabled:false,sites:[]},tracking:{require_unique_topology:false,initial_search_radius_m:meters(Math.max(n("widthNm"),n("heightNm"))*.2),maximum_jump_m:2e-9},thermal_control:{sensor:"peak",switch_off_K:15,restart_below_K:14.5,hard_stop_K:15.45,minimum_dwell_steps:50},timing:{dark_steps:200,max_steps:Math.round(n("steps")),sample_every:Math.round(n("sampleEvery")),checkpoint_every:200,stall_window_steps:1000,stall_consecutive_windows:3,minimum_progress_per_window_nm:.05,max_wall_hours:12},output:{field_snapshot_every:50},live_preview:{enabled:true,every_steps:200,history_frames:20,page_refresh_seconds:10},profiling:{enabled:true},output_directory:`benchmark_results/${name}`}}
return {_documentation:documentation,simulation_config:`configs/simulations/${name}_simulation.json`,run:{steps:Math.round(n("steps")),dt:femto(n("dtFs")),sample_every:Math.round(n("sampleEvery"))},sweeps:{"diagnostics.applied_Bz_T":[n("fieldT")],"diagnostics.target_current_A":[n("currentNa")*1e-9]},transport:{drive_mode:"current",target_current_A:n("currentNa")*1e-9,relative_tolerance:.001,max_voltage_iterations:8,voltage_limit_V:.01},magnetic_field:{applied_Bz_T:n("fieldT"),gauge:"symmetric",calculate_self_field:$("selfField").checked,observation_height_m:5e-9,source_stride:1},validity:{maximum_distance_from_Tc:.2,maximum_thickness_over_xi:1,maximum_thickness_over_lambda:1,maximum_spacing_over_xi:.5},initial_conditions:{temperature_hotspot:{enabled:false},vortices},vortex_detection:{amplitude_floor:1e-8},vortex_tracking:{max_displacement_cells:8},fluxoid:{contour_inset_fraction:.2},output:{directory:`benchmark_results/${name}`,plots:true,kymograph_centerline:"horizontal",dpi:150,vector_stride:5,gif:{enabled:true,fps:4}}}}
function project(){return {format:"shs-config-editor-v2",preset:state.preset,inputs:Object.fromEntries(inputIds.map(id=>[id,$(id).type==="checkbox"?$(id).checked:$(id).value])),holes:state.holes,vortices:state.vortices,laser:state.laser}}
function download(name,data){const blob=new Blob([JSON.stringify(data,null,2)+"\n"],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$("status").textContent=`Downloaded ${name}`}
$("downloadGeometry").onclick=()=>download(`${cleanName()}_geometry.json`,geometry());$("downloadSimulation").onclick=()=>download(`${cleanName()}_simulation.json`,simulation());$("downloadDiagnostics").onclick=()=>download(`${cleanName()}_experiment.json`,diagnostics());$("downloadProject").onclick=()=>download(`${cleanName()}_project.json`,project());
$("downloadAll").onclick=()=>{download(`${cleanName()}_geometry.json`,geometry());setTimeout(()=>download(`${cleanName()}_simulation.json`,simulation()),150);setTimeout(()=>download(`${cleanName()}_experiment.json`,diagnostics()),300)};
$("importProject").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const p=JSON.parse(await file.text());if(!["shs-config-editor-v1","shs-config-editor-v2"].includes(p.format))throw Error("Unknown editor format");Object.entries(p.inputs||{}).forEach(([id,v])=>{if($(id))$(id).type==="checkbox"?$(id).checked=v:$(id).value=v});state.preset=p.preset||$("experimentPreset").value||"basic_film";$("experimentPreset").value=state.preset;state.holes=p.holes||[];state.vortices=p.vortices||[];state.laser=p.laser||[];state.selected=null;renderEditor();updateContext();resize();$("status").textContent=`Imported ${file.name}`}catch(err){$("status").textContent=`Import failed: ${err.message}`}};
$("applyPreset").onclick=applyPreset;$("experimentPreset").onchange=updateContext;$("resetProject").onclick=applyPreset;inputIds.forEach(id=>$(id).addEventListener("input",id==="experimentPreset"?updateContext:draw));window.addEventListener("resize",resize);new ResizeObserver(resize).observe(canvas.parentElement);applyPreset();
